# Generated by Django 2.2.26 on 2022-07-18 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fundJSV_I', models.TextField()),
                ('fundJSV_II', models.TextField()),
                ('fundJSV_III', models.TextField()),
            ],
        ),
    ]
