# Generated by Django 2.2.26 on 2022-07-18 21:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fund', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FundJSV_I_members',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('member_I', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fundjsv_i_members_member_I', to='fund.Fund')),
                ('member_II', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fundjsv_i_members_member_II', to='fund.Fund')),
                ('member_III', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fundjsv_i_members_member_III', to='fund.Fund')),
                ('member_IV', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fundjsv_i_members_member_IV', to='fund.Fund')),
                ('member_V', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='fundjsv_i_members_member_V', to='fund.Fund')),
            ],
        ),
    ]
