# Generated by Django 2.2.26 on 2022-07-19 02:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("companies", "0001_initial"),
        ("company_name", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="company_name",
            name="company_name",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="company_name_company_name",
                to="companies.Companies",
            ),
        ),
    ]
